version: '3.9'

networks:
  isolated_network:
    driver: bridge


services:

  postgres-inventory:
    image: postgres
    ports:
      - "5433:5432"
    container_name: postgres-inventory
    networks:
      - isolated_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inventory-service
    volumes:
      - ./data/inventory:/var/lib/postgresql/data
      - ./init/inventory/init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-order:
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres-order
    networks:
      - isolated_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=order-service
    volumes:
      - ./data/order:/var/lib/postgresql/data
      - ./init/order/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    container_name: pgadmin-multiple
    networks:
      - isolated_network
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password

